haxe build.hxml || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
